# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_app', '0002_auto_20190827_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
