# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_app', '0003_user_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fragrance',
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance',
            field=models.ManyToManyField(related_name='products', to='candle_app.Fragrance'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='products', to='candle_app.Size'),
        ),
    ]
