# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candle_app', '0006_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='session_id',
            new_name='cart_id',
        ),
    ]
