# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_app', '0007_auto_20190827_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
