# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_app', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
